image: elixir:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /root/.cargo
    - apt-cache/

services:
  - postgres:latest

variables:
  POSTGRES_DB: test_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - apt-get update && apt-get -o dir::cache::archives="apt-cache" -y install postgresql-client
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
  - export PATH=/root/.cargo/bin:${PATH}
  - source $HOME/.cargo/env
  - mix local.hex --force
  - mix local.rebar --force

mix-deps:
  script:
    - mix deps.get
    - mix deps.compile

mix-ecto:
  script:
    - mix ecto.create
    - mix ecto.migrate

build:
  script:
    - mix test
