version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data
    configs:
      - source: ./data/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
    configs:
      - source: ./data/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - default
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgis/postgis
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./tmp/rabbitmq/data/:/var/lib/rabbitmq/
      - ./tmp/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default

  #############################################################################

  happ:
    build: .
    ports:
      - "4000:4000"
    networks:
      - default
    depends_on:
      - "postgres"

  #############################################################################

networks:
  default:
    driver: bridge